# Generated by Django 4.2.27 on 2026-02-13 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('db_type', models.CharField(choices=[('oracle', 'Oracle'), ('mysql', 'MySQL'), ('postgres', 'PostgreSQL')], default='oracle', max_length=20)),
                ('host', models.CharField(max_length=200)),
                ('port', models.PositiveIntegerField(default=1521)),
                ('user', models.CharField(max_length=200)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('database_name', models.CharField(help_text='MySQL/Postgres: DB name | Oracle: SERVICE_NAME (ex: FREEPDB1)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('execute_at', models.DateTimeField(blank=True, null=True)),
                ('is_periodic', models.BooleanField(default=False)),
                ('periodic_type', models.CharField(blank=True, choices=[('daily', 'Chaque jour'), ('weekly', 'Chaque semaine'), ('monthly', 'Chaque mois')], max_length=10, null=True)),
                ('periodic_time', models.TimeField(blank=True, null=True)),
                ('periodic_weekday', models.CharField(blank=True, choices=[('mon', 'Lundi'), ('tue', 'Mardi'), ('wed', 'Mercredi'), ('thu', 'Jeudi'), ('fri', 'Vendredi'), ('sat', 'Samedi'), ('sun', 'Dimanche')], max_length=3, null=True)),
                ('periodic_monthday', models.PositiveIntegerField(blank=True, null=True)),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SqlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sql_text', models.TextField(verbose_name='Requête SQL')),
                ('enable_totals', models.BooleanField(default=False)),
                ('total_columns', models.JSONField(blank=True, default=list)),
                ('total_label', models.CharField(blank=True, default='TOTAL', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='app_rapports.databaseconnection')),
            ],
        ),
        migrations.CreateModel(
            name='ReportExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Succès'), ('error', 'Erreur')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='app_rapports.sqlquery')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app_rapports.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='queries',
            field=models.ManyToManyField(related_name='reports', to='app_rapports.sqlquery'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_password_change', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportQueryParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_parameters', to='app_rapports.sqlquery')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_parameters', to='app_rapports.report')),
            ],
            options={
                'unique_together': {('report', 'query', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ReportEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('email_type', models.CharField(choices=[('to', 'TO'), ('cc', 'CC')], max_length=2)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='app_rapports.report')),
            ],
            options={
                'unique_together': {('report', 'email', 'email_type')},
            },
        ),
    ]
